name: linting, testing, building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 18
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
        node-version: ${{ matrix.node-version }}
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: build production
        run: npm run build:wp
      - name: linting ts
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit tests
        run: npm run test:unit